//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundingPilotSystem.Services.MasterDataProviderService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FundingPilotSystem.Services.MasterDataProviderService.IMasterDataProviderService")]
    public interface IMasterDataProviderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetFPApplication", ReplyAction="http://tempuri.org/ICommonService/SetFPApplicationResponse")]
        void SetFPApplication(FundingPilotSystem.Common.FPApplication fpApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetFPApplication", ReplyAction="http://tempuri.org/ICommonService/SetFPApplicationResponse")]
        System.Threading.Tasks.Task SetFPApplicationAsync(FundingPilotSystem.Common.FPApplication fpApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataProviderService/GetCountries", ReplyAction="http://tempuri.org/IMasterDataProviderService/GetCountriesResponse")]
        System.Collections.Generic.List<FundingPilotSystem.VM.CountryListVM> GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataProviderService/GetCountries", ReplyAction="http://tempuri.org/IMasterDataProviderService/GetCountriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FundingPilotSystem.VM.CountryListVM>> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataProviderService/GetCountryOfOperations", ReplyAction="http://tempuri.org/IMasterDataProviderService/GetCountryOfOperationsResponse")]
        System.Collections.Generic.List<FundingPilotSystem.VM.CountryOfOperationVM> GetCountryOfOperations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataProviderService/GetCountryOfOperations", ReplyAction="http://tempuri.org/IMasterDataProviderService/GetCountryOfOperationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FundingPilotSystem.VM.CountryOfOperationVM>> GetCountryOfOperationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataProviderService/GetSystemModules", ReplyAction="http://tempuri.org/IMasterDataProviderService/GetSystemModulesResponse")]
        System.Collections.Generic.List<FundingPilotSystem.VM.SystemModuleVM> GetSystemModules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDataProviderService/GetSystemModules", ReplyAction="http://tempuri.org/IMasterDataProviderService/GetSystemModulesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FundingPilotSystem.VM.SystemModuleVM>> GetSystemModulesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterDataProviderServiceChannel : FundingPilotSystem.Services.MasterDataProviderService.IMasterDataProviderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterDataProviderServiceClient : System.ServiceModel.ClientBase<FundingPilotSystem.Services.MasterDataProviderService.IMasterDataProviderService>, FundingPilotSystem.Services.MasterDataProviderService.IMasterDataProviderService
    {
        
        public MasterDataProviderServiceClient()
        {
        }
        
        public MasterDataProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MasterDataProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MasterDataProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MasterDataProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SetFPApplication(FundingPilotSystem.Common.FPApplication fpApplication)
        {
            base.Channel.SetFPApplication(fpApplication);
        }
        
        public System.Threading.Tasks.Task SetFPApplicationAsync(FundingPilotSystem.Common.FPApplication fpApplication)
        {
            return base.Channel.SetFPApplicationAsync(fpApplication);
        }
        
        public System.Collections.Generic.List<FundingPilotSystem.VM.CountryListVM> GetCountries()
        {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FundingPilotSystem.VM.CountryListVM>> GetCountriesAsync()
        {
            return base.Channel.GetCountriesAsync();
        }
        
        public System.Collections.Generic.List<FundingPilotSystem.VM.CountryOfOperationVM> GetCountryOfOperations()
        {
            return base.Channel.GetCountryOfOperations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FundingPilotSystem.VM.CountryOfOperationVM>> GetCountryOfOperationsAsync()
        {
            return base.Channel.GetCountryOfOperationsAsync();
        }
        
        public System.Collections.Generic.List<FundingPilotSystem.VM.SystemModuleVM> GetSystemModules()
        {
            return base.Channel.GetSystemModules();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FundingPilotSystem.VM.SystemModuleVM>> GetSystemModulesAsync()
        {
            return base.Channel.GetSystemModulesAsync();
        }
    }
}
