//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundingPilotSystem.Services.RegistrationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FundingPilotSystem.Services.RegistrationService.IRegistrationServices")]
    public interface IRegistrationServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetFPApplication", ReplyAction="http://tempuri.org/ICommonService/SetFPApplicationResponse")]
        void SetFPApplication(FundingPilotSystem.Common.FPApplication fpApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetFPApplication", ReplyAction="http://tempuri.org/ICommonService/SetFPApplicationResponse")]
        System.Threading.Tasks.Task SetFPApplicationAsync(FundingPilotSystem.Common.FPApplication fpApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequest", ReplyAction="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequestResponse")]
        int SaveUserRegistrationRequest(FundingPilotSystem.VM.UserRegistrationRequestsViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequest", ReplyAction="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequestResponse")]
        System.Threading.Tasks.Task<int> SaveUserRegistrationRequestAsync(FundingPilotSystem.VM.UserRegistrationRequestsViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationServices/isDuplicateUserEmailAddress", ReplyAction="http://tempuri.org/IRegistrationServices/isDuplicateUserEmailAddressResponse")]
        bool isDuplicateUserEmailAddress(byte[] emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationServices/isDuplicateUserEmailAddress", ReplyAction="http://tempuri.org/IRegistrationServices/isDuplicateUserEmailAddressResponse")]
        System.Threading.Tasks.Task<bool> isDuplicateUserEmailAddressAsync(byte[] emailAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationServicesChannel : FundingPilotSystem.Services.RegistrationService.IRegistrationServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServicesClient : System.ServiceModel.ClientBase<FundingPilotSystem.Services.RegistrationService.IRegistrationServices>, FundingPilotSystem.Services.RegistrationService.IRegistrationServices
    {
        
        public RegistrationServicesClient()
        {
        }
        
        public RegistrationServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RegistrationServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RegistrationServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RegistrationServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SetFPApplication(FundingPilotSystem.Common.FPApplication fpApplication)
        {
            base.Channel.SetFPApplication(fpApplication);
        }
        
        public System.Threading.Tasks.Task SetFPApplicationAsync(FundingPilotSystem.Common.FPApplication fpApplication)
        {
            return base.Channel.SetFPApplicationAsync(fpApplication);
        }
        
        public int SaveUserRegistrationRequest(FundingPilotSystem.VM.UserRegistrationRequestsViewModel model)
        {
            return base.Channel.SaveUserRegistrationRequest(model);
        }
        
        public System.Threading.Tasks.Task<int> SaveUserRegistrationRequestAsync(FundingPilotSystem.VM.UserRegistrationRequestsViewModel model)
        {
            return base.Channel.SaveUserRegistrationRequestAsync(model);
        }
        
        public bool isDuplicateUserEmailAddress(byte[] emailAddress)
        {
            return base.Channel.isDuplicateUserEmailAddress(emailAddress);
        }
        
        public System.Threading.Tasks.Task<bool> isDuplicateUserEmailAddressAsync(byte[] emailAddress)
        {
            return base.Channel.isDuplicateUserEmailAddressAsync(emailAddress);
        }
    }
}
