//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundingPilotSystem.Services.FPUserProfile.RegistrationService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRegistrationRequestsViewModel", Namespace="http://schemas.datacontract.org/2004/07/FundingPilotSystem.VM.FPUserProfile")]
    public partial class UserRegistrationRequestsViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<FundingPilotSystem.Domain.FPMasterValues.tblCountryOfOperationDto> CountriesOfOperationField;
        
        private int CountryOfRegistrationField;
        
        private int IdField;
        
        private byte[] LoginPasswordField;
        
        private bool NewsLetterField;
        
        private string PasswordField;
        
        private System.DateTime RegistrationDateField;
        
        private string RegistrationIPField;
        
        private byte[] UserEmailField;
        
        private string UserEmailAddressField;
        
        private int UserStatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FundingPilotSystem.Domain.FPMasterValues.tblCountryOfOperationDto> CountriesOfOperation
        {
            get
            {
                return this.CountriesOfOperationField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CountriesOfOperationField, value) != true))
                {
                    this.CountriesOfOperationField = value;
                    this.RaisePropertyChanged("CountriesOfOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryOfRegistration
        {
            get
            {
                return this.CountryOfRegistrationField;
            }
            set
            {
                if ((this.CountryOfRegistrationField.Equals(value) != true))
                {
                    this.CountryOfRegistrationField = value;
                    this.RaisePropertyChanged("CountryOfRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] LoginPassword
        {
            get
            {
                return this.LoginPasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LoginPasswordField, value) != true))
                {
                    this.LoginPasswordField = value;
                    this.RaisePropertyChanged("LoginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NewsLetter
        {
            get
            {
                return this.NewsLetterField;
            }
            set
            {
                if ((this.NewsLetterField.Equals(value) != true))
                {
                    this.NewsLetterField = value;
                    this.RaisePropertyChanged("NewsLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PasswordField, value) != true))
                {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate
        {
            get
            {
                return this.RegistrationDateField;
            }
            set
            {
                if ((this.RegistrationDateField.Equals(value) != true))
                {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationIP
        {
            get
            {
                return this.RegistrationIPField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RegistrationIPField, value) != true))
                {
                    this.RegistrationIPField = value;
                    this.RaisePropertyChanged("RegistrationIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] UserEmail
        {
            get
            {
                return this.UserEmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true))
                {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmailAddress
        {
            get
            {
                return this.UserEmailAddressField;
            }
            set
            {
                if ((object.ReferenceEquals(this.UserEmailAddressField, value) != true))
                {
                    this.UserEmailAddressField = value;
                    this.RaisePropertyChanged("UserEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserStatus
        {
            get
            {
                return this.UserStatusField;
            }
            set
            {
                if ((this.UserStatusField.Equals(value) != true))
                {
                    this.UserStatusField = value;
                    this.RaisePropertyChanged("UserStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FundingPilotSystem.Services.FPUserProfile.RegistrationService.IRegistrationServic" +
        "es")]
    public interface IRegistrationServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetFPApplication", ReplyAction="http://tempuri.org/ICommonService/SetFPApplicationResponse")]
        void SetFPApplication(FundingPilotSystem.Domain.SolutionDto.FPApplication fpApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetFPApplication", ReplyAction="http://tempuri.org/ICommonService/SetFPApplicationResponse")]
        System.Threading.Tasks.Task SetFPApplicationAsync(FundingPilotSystem.Domain.SolutionDto.FPApplication fpApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequest", ReplyAction="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequestResponse")]
        int SaveUserRegistrationRequest(FundingPilotSystem.Services.FPUserProfile.RegistrationService.UserRegistrationRequestsViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequest", ReplyAction="http://tempuri.org/IRegistrationServices/SaveUserRegistrationRequestResponse")]
        System.Threading.Tasks.Task<int> SaveUserRegistrationRequestAsync(FundingPilotSystem.Services.FPUserProfile.RegistrationService.UserRegistrationRequestsViewModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationServicesChannel : FundingPilotSystem.Services.FPUserProfile.RegistrationService.IRegistrationServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationServicesClient : System.ServiceModel.ClientBase<FundingPilotSystem.Services.FPUserProfile.RegistrationService.IRegistrationServices>, FundingPilotSystem.Services.FPUserProfile.RegistrationService.IRegistrationServices
    {
        
        public RegistrationServicesClient()
        {
        }
        
        public RegistrationServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RegistrationServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RegistrationServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RegistrationServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void SetFPApplication(FundingPilotSystem.Domain.SolutionDto.FPApplication fpApplication)
        {
            base.Channel.SetFPApplication(fpApplication);
        }
        
        public System.Threading.Tasks.Task SetFPApplicationAsync(FundingPilotSystem.Domain.SolutionDto.FPApplication fpApplication)
        {
            return base.Channel.SetFPApplicationAsync(fpApplication);
        }
        
        public int SaveUserRegistrationRequest(FundingPilotSystem.Services.FPUserProfile.RegistrationService.UserRegistrationRequestsViewModel model)
        {
            return base.Channel.SaveUserRegistrationRequest(model);
        }
        
        public System.Threading.Tasks.Task<int> SaveUserRegistrationRequestAsync(FundingPilotSystem.Services.FPUserProfile.RegistrationService.UserRegistrationRequestsViewModel model)
        {
            return base.Channel.SaveUserRegistrationRequestAsync(model);
        }
    }
}
