//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundingPilotSystem.UnifiedDataStore.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailLog
    {
        public int Id { get; set; }
        public int Process { get; set; }
        public string EmailBody { get; set; }
        public string Receiver { get; set; }
        public System.DateTime SentTime { get; set; }
    
        public virtual tblProcess tblProcess { get; set; }
    }
}
