//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FundingPilotSystem.UnifiedDataStore.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLoginCredential
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte[] LoginPassword { get; set; }
        public Nullable<System.DateTime> LastPasswordChanged { get; set; }
        public Nullable<System.DateTime> LastFailedLogin { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public bool IsLocked { get; set; }
        public int UserType { get; set; }
        public byte[] Key { get; set; }
        public byte[] Salt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string IPAddressOfLastAction { get; set; }
    }
}
