
insert into tblCountryList (Id,CountryISOCode,Country) values(2,'AX','ÅLAND ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(3,'AL','ALBANIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(4,'DZ','ALGERIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(5,'AS','AMERICAN SAMOA')
insert into tblCountryList (Id,CountryISOCode,Country) values(6,'AD','ANDORRA')
insert into tblCountryList (Id,CountryISOCode,Country) values(7,'AO','ANGOLA')
insert into tblCountryList (Id,CountryISOCode,Country) values(8,'AI','ANGUILLA')
insert into tblCountryList (Id,CountryISOCode,Country) values(9,'AQ','ANTARCTICA')
insert into tblCountryList (Id,CountryISOCode,Country) values(10,'AG','ANTIGUA AND BARBUDA')
insert into tblCountryList (Id,CountryISOCode,Country) values(11,'AR','ARGENTINA')
insert into tblCountryList (Id,CountryISOCode,Country) values(12,'AM','ARMENIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(13,'AW','ARUBA')
insert into tblCountryList (Id,CountryISOCode,Country) values(14,'AU','AUSTRALIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(15,'AT','AUSTRIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(16,'AZ','AZERBAIJAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(17,'BS','BAHAMAS')
insert into tblCountryList (Id,CountryISOCode,Country) values(18,'BH','BAHRAIN')
insert into tblCountryList (Id,CountryISOCode,Country) values(19,'BD','BANGLADESH')
insert into tblCountryList (Id,CountryISOCode,Country) values(20,'BB','BARBADOS')
insert into tblCountryList (Id,CountryISOCode,Country) values(21,'BY','BELARUS')
insert into tblCountryList (Id,CountryISOCode,Country) values(22,'BE','BELGIUM')
insert into tblCountryList (Id,CountryISOCode,Country) values(23,'BZ','BELIZE')
insert into tblCountryList (Id,CountryISOCode,Country) values(24,'BJ','BENIN')
insert into tblCountryList (Id,CountryISOCode,Country) values(25,'BM','BERMUDA')
insert into tblCountryList (Id,CountryISOCode,Country) values(26,'BT','BHUTAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(27,'BO','BOLIVIA, PLURINATIONAL STATE OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(28,'BQ','BONAIRE, SINT EUSTATIUS AND SABA')
insert into tblCountryList (Id,CountryISOCode,Country) values(29,'BA','BOSNIA AND HERZEGOVINA')
insert into tblCountryList (Id,CountryISOCode,Country) values(30,'BW','BOTSWANA')
insert into tblCountryList (Id,CountryISOCode,Country) values(31,'BV','BOUVET ISLAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(32,'BR','BRAZIL')
insert into tblCountryList (Id,CountryISOCode,Country) values(33,'IO','BRITISH INDIAN OCEAN TERRITORY')
insert into tblCountryList (Id,CountryISOCode,Country) values(34,'BN','BRUNEI DARUSSALAM')
insert into tblCountryList (Id,CountryISOCode,Country) values(35,'BG','BULGARIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(36,'BF','BURKINA FASO')
insert into tblCountryList (Id,CountryISOCode,Country) values(37,'BI','BURUNDI')
insert into tblCountryList (Id,CountryISOCode,Country) values(38,'KH','CAMBODIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(39,'CM','CAMEROON')
insert into tblCountryList (Id,CountryISOCode,Country) values(40,'CA','CANADA')
insert into tblCountryList (Id,CountryISOCode,Country) values(41,'CV','CAPE VERDE')
insert into tblCountryList (Id,CountryISOCode,Country) values(42,'KY','CAYMAN ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(43,'CF','CENTRAL AFRICAN REPUBLIC')
insert into tblCountryList (Id,CountryISOCode,Country) values(44,'TD','CHAD')
insert into tblCountryList (Id,CountryISOCode,Country) values(45,'CL','CHILE')
insert into tblCountryList (Id,CountryISOCode,Country) values(46,'CN','CHINA')
insert into tblCountryList (Id,CountryISOCode,Country) values(47,'CX','CHRISTMAS ISLAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(48,'CC','COCOS (KEELING) ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(49,'CO','COLOMBIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(50,'KM','COMOROS')
insert into tblCountryList (Id,CountryISOCode,Country) values(51,'CG','CONGO')
insert into tblCountryList (Id,CountryISOCode,Country) values(52,'CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE')
insert into tblCountryList (Id,CountryISOCode,Country) values(53,'CK','COOK ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(54,'CR','COSTA RICA')
insert into tblCountryList (Id,CountryISOCode,Country) values(55,'CI','CÔTE D''IVOIRE')
insert into tblCountryList (Id,CountryISOCode,Country) values(56,'HR','CROATIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(57,'CU','CUBA')
insert into tblCountryList (Id,CountryISOCode,Country) values(58,'CW','CURAÇAO')
insert into tblCountryList (Id,CountryISOCode,Country) values(59,'CY','CYPRUS')
insert into tblCountryList (Id,CountryISOCode,Country) values(60,'CZ','CZECH REPUBLIC')
insert into tblCountryList (Id,CountryISOCode,Country) values(61,'DK','DENMARK')
insert into tblCountryList (Id,CountryISOCode,Country) values(62,'DJ','DJIBOUTI')
insert into tblCountryList (Id,CountryISOCode,Country) values(63,'DM','DOMINICA')
insert into tblCountryList (Id,CountryISOCode,Country) values(64,'DO','DOMINICAN REPUBLIC')
insert into tblCountryList (Id,CountryISOCode,Country) values(65,'EC','ECUADOR')
insert into tblCountryList (Id,CountryISOCode,Country) values(66,'EG','EGYPT')
insert into tblCountryList (Id,CountryISOCode,Country) values(67,'SV','EL SALVADOR')
insert into tblCountryList (Id,CountryISOCode,Country) values(68,'GQ','EQUATORIAL GUINEA')
insert into tblCountryList (Id,CountryISOCode,Country) values(69,'ER','ERITREA')
insert into tblCountryList (Id,CountryISOCode,Country) values(70,'EE','ESTONIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(71,'ET','ETHIOPIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(72,'FK','FALKLAND ISLANDS (MALVINAS)')
insert into tblCountryList (Id,CountryISOCode,Country) values(73,'FO','FAROE ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(74,'FJ','FIJI')
insert into tblCountryList (Id,CountryISOCode,Country) values(75,'FI','FINLAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(76,'FR','FRANCE')
insert into tblCountryList (Id,CountryISOCode,Country) values(77,'GF','FRENCH GUIANA')
insert into tblCountryList (Id,CountryISOCode,Country) values(78,'PF','FRENCH POLYNESIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(79,'TF','FRENCH SOUTHERN TERRITORIES')
insert into tblCountryList (Id,CountryISOCode,Country) values(80,'GA','GABON')
insert into tblCountryList (Id,CountryISOCode,Country) values(81,'GM','GAMBIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(82,'GE','GEORGIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(83,'DE','GERMANY')
insert into tblCountryList (Id,CountryISOCode,Country) values(84,'GH','GHANA')
insert into tblCountryList (Id,CountryISOCode,Country) values(85,'GI','GIBRALTAR')
insert into tblCountryList (Id,CountryISOCode,Country) values(86,'GR','GREECE')
insert into tblCountryList (Id,CountryISOCode,Country) values(87,'GL','GREENLAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(88,'GD','GRENADA')
insert into tblCountryList (Id,CountryISOCode,Country) values(89,'GP','GUADELOUPE')
insert into tblCountryList (Id,CountryISOCode,Country) values(90,'GU','GUAM')
insert into tblCountryList (Id,CountryISOCode,Country) values(91,'GT','GUATEMALA')
insert into tblCountryList (Id,CountryISOCode,Country) values(92,'GG','GUERNSEY')
insert into tblCountryList (Id,CountryISOCode,Country) values(93,'GN','GUINEA')
insert into tblCountryList (Id,CountryISOCode,Country) values(94,'GW','GUINEA-BISSAU')
insert into tblCountryList (Id,CountryISOCode,Country) values(95,'GY','GUYANA')
insert into tblCountryList (Id,CountryISOCode,Country) values(96,'HT','HAITI')
insert into tblCountryList (Id,CountryISOCode,Country) values(97,'HM','HEARD ISLAND AND MCDONALD ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(98,'VA','HOLY SEE (VATICAN CITY STATE)')
insert into tblCountryList (Id,CountryISOCode,Country) values(99,'HN','HONDURAS')
insert into tblCountryList (Id,CountryISOCode,Country) values(100,'HK','HONG KONG')
insert into tblCountryList (Id,CountryISOCode,Country) values(101,'HU','HUNGARY')
insert into tblCountryList (Id,CountryISOCode,Country) values(102,'IS','ICELAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(103,'IN','INDIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(104,'ID','INDONESIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(105,'IR','IRAN, ISLAMIC REPUBLIC OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(106,'IQ','IRAQ')
insert into tblCountryList (Id,CountryISOCode,Country) values(107,'IE','IRELAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(108,'IM','ISLE OF MAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(109,'IL','ISRAEL')
insert into tblCountryList (Id,CountryISOCode,Country) values(110,'IT','ITALY')
insert into tblCountryList (Id,CountryISOCode,Country) values(111,'JM','JAMAICA')
insert into tblCountryList (Id,CountryISOCode,Country) values(112,'JP','JAPAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(113,'JE','JERSEY')
insert into tblCountryList (Id,CountryISOCode,Country) values(114,'JO','JORDAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(115,'KZ','KAZAKHSTAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(116,'KE','KENYA')
insert into tblCountryList (Id,CountryISOCode,Country) values(117,'KI','KIRIBATI')
insert into tblCountryList (Id,CountryISOCode,Country) values(118,'KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(119,'KR','KOREA, REPUBLIC OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(120,'KW','KUWAIT')
insert into tblCountryList (Id,CountryISOCode,Country) values(121,'KG','KYRGYZSTAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(122,'LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC')
insert into tblCountryList (Id,CountryISOCode,Country) values(123,'LV','LATVIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(124,'LB','LEBANON')
insert into tblCountryList (Id,CountryISOCode,Country) values(125,'LS','LESOTHO')
insert into tblCountryList (Id,CountryISOCode,Country) values(126,'LR','LIBERIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(127,'LY','LIBYA')
insert into tblCountryList (Id,CountryISOCode,Country) values(128,'LI','LIECHTENSTEIN')
insert into tblCountryList (Id,CountryISOCode,Country) values(129,'LT','LITHUANIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(130,'LU','LUXEMBOURG')
insert into tblCountryList (Id,CountryISOCode,Country) values(131,'MO','MACAO')
insert into tblCountryList (Id,CountryISOCode,Country) values(132,'MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(133,'MG','MADAGASCAR')
insert into tblCountryList (Id,CountryISOCode,Country) values(134,'MW','MALAWI')
insert into tblCountryList (Id,CountryISOCode,Country) values(135,'MY','MALAYSIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(136,'MV','MALDIVES')
insert into tblCountryList (Id,CountryISOCode,Country) values(137,'ML','MALI')
insert into tblCountryList (Id,CountryISOCode,Country) values(138,'MT','MALTA')
insert into tblCountryList (Id,CountryISOCode,Country) values(139,'MH','MARSHALL ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(140,'MQ','MARTINIQUE')
insert into tblCountryList (Id,CountryISOCode,Country) values(141,'MR','MAURITANIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(142,'MU','MAURITIUS')
insert into tblCountryList (Id,CountryISOCode,Country) values(143,'YT','MAYOTTE')
insert into tblCountryList (Id,CountryISOCode,Country) values(144,'MX','MEXICO')
insert into tblCountryList (Id,CountryISOCode,Country) values(145,'FM','MICRONESIA, FEDERATED STATES OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(146,'MD','MOLDOVA, REPUBLIC OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(147,'MC','MONACO')
insert into tblCountryList (Id,CountryISOCode,Country) values(148,'MN','MONGOLIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(149,'ME','MONTENEGRO')
insert into tblCountryList (Id,CountryISOCode,Country) values(150,'MS','MONTSERRAT')
insert into tblCountryList (Id,CountryISOCode,Country) values(151,'MA','MOROCCO')
insert into tblCountryList (Id,CountryISOCode,Country) values(152,'MZ','MOZAMBIQUE')
insert into tblCountryList (Id,CountryISOCode,Country) values(153,'MM','MYANMAR')
insert into tblCountryList (Id,CountryISOCode,Country) values(154,'NA','NAMIBIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(155,'NR','NAURU')
insert into tblCountryList (Id,CountryISOCode,Country) values(156,'NP','NEPAL')
insert into tblCountryList (Id,CountryISOCode,Country) values(157,'NL','NETHERLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(158,'NC','NEW CALEDONIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(159,'NZ','NEW ZEALAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(160,'NI','NICARAGUA')
insert into tblCountryList (Id,CountryISOCode,Country) values(161,'NE','NIGER')
insert into tblCountryList (Id,CountryISOCode,Country) values(162,'NG','NIGERIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(163,'NU','NIUE')
insert into tblCountryList (Id,CountryISOCode,Country) values(164,'NF','NORFOLK ISLAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(165,'MP','NORTHERN MARIANA ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(166,'NO','NORWAY')
insert into tblCountryList (Id,CountryISOCode,Country) values(167,'OM','OMAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(168,'PK','PAKISTAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(169,'PW','PALAU')
insert into tblCountryList (Id,CountryISOCode,Country) values(170,'PS','PALESTINE, STATE OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(171,'PA','PANAMA')
insert into tblCountryList (Id,CountryISOCode,Country) values(172,'PG','PAPUA NEW GUINEA')
insert into tblCountryList (Id,CountryISOCode,Country) values(173,'PY','PARAGUAY')
insert into tblCountryList (Id,CountryISOCode,Country) values(174,'PE','PERU')
insert into tblCountryList (Id,CountryISOCode,Country) values(175,'PH','PHILIPPINES')
insert into tblCountryList (Id,CountryISOCode,Country) values(176,'PN','PITCAIRN')
insert into tblCountryList (Id,CountryISOCode,Country) values(177,'PL','POLAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(178,'PT','PORTUGAL')
insert into tblCountryList (Id,CountryISOCode,Country) values(179,'PR','PUERTO RICO')
insert into tblCountryList (Id,CountryISOCode,Country) values(180,'QA','QATAR')
insert into tblCountryList (Id,CountryISOCode,Country) values(181,'RE','RÉUNION')
insert into tblCountryList (Id,CountryISOCode,Country) values(182,'RO','ROMANIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(183,'RU','RUSSIAN FEDERATION')
insert into tblCountryList (Id,CountryISOCode,Country) values(184,'RW','RWANDA')
insert into tblCountryList (Id,CountryISOCode,Country) values(185,'BL','SAINT BARTHÉLEMY')
insert into tblCountryList (Id,CountryISOCode,Country) values(186,'SH','SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA')
insert into tblCountryList (Id,CountryISOCode,Country) values(187,'KN','SAINT KITTS AND NEVIS')
insert into tblCountryList (Id,CountryISOCode,Country) values(188,'LC','SAINT LUCIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(189,'MF','SAINT MARTIN (FRENCH PART)')
insert into tblCountryList (Id,CountryISOCode,Country) values(190,'PM','SAINT PIERRE AND MIQUELON')
insert into tblCountryList (Id,CountryISOCode,Country) values(191,'VC','SAINT VINCENT AND THE GRENADINES')
insert into tblCountryList (Id,CountryISOCode,Country) values(192,'WS','SAMOA')
insert into tblCountryList (Id,CountryISOCode,Country) values(193,'SM','SAN MARINO')
insert into tblCountryList (Id,CountryISOCode,Country) values(194,'ST','SAO TOME AND PRINCIPE')
insert into tblCountryList (Id,CountryISOCode,Country) values(195,'SA','SAUDI ARABIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(196,'SN','SENEGAL')
insert into tblCountryList (Id,CountryISOCode,Country) values(197,'RS','SERBIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(198,'SC','SEYCHELLES')
insert into tblCountryList (Id,CountryISOCode,Country) values(199,'SL','SIERRA LEONE')
insert into tblCountryList (Id,CountryISOCode,Country) values(200,'SG','SINGAPORE')
insert into tblCountryList (Id,CountryISOCode,Country) values(201,'SX','SINT MAARTEN (DUTCH PART)')
insert into tblCountryList (Id,CountryISOCode,Country) values(202,'SK','SLOVAKIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(203,'SI','SLOVENIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(204,'SB','SOLOMON ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(205,'SO','SOMALIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(206,'ZA','SOUTH AFRICA')
insert into tblCountryList (Id,CountryISOCode,Country) values(207,'GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(208,'SS','SOUTH SUDAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(209,'ES','SPAIN')
insert into tblCountryList (Id,CountryISOCode,Country) values(210,'LK','SRI LANKA')
insert into tblCountryList (Id,CountryISOCode,Country) values(211,'SD','SUDAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(212,'SR','SURINAME')
insert into tblCountryList (Id,CountryISOCode,Country) values(213,'SJ','SVALBARD AND JAN MAYEN')
insert into tblCountryList (Id,CountryISOCode,Country) values(214,'SZ','SWAZILAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(215,'SE','SWEDEN')
insert into tblCountryList (Id,CountryISOCode,Country) values(216,'CH','SWITZERLAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(217,'SY','SYRIAN ARAB REPUBLIC')
insert into tblCountryList (Id,CountryISOCode,Country) values(218,'TW','TAIWAN, PROVINCE OF CHINA')
insert into tblCountryList (Id,CountryISOCode,Country) values(219,'TJ','TAJIKISTAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(220,'TZ','TANZANIA, UNITED REPUBLIC OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(221,'TH','THAILAND')
insert into tblCountryList (Id,CountryISOCode,Country) values(222,'TL','TIMOR-LESTE')
insert into tblCountryList (Id,CountryISOCode,Country) values(223,'TG','TOGO')
insert into tblCountryList (Id,CountryISOCode,Country) values(224,'TK','TOKELAU')
insert into tblCountryList (Id,CountryISOCode,Country) values(225,'TO','TONGA')
insert into tblCountryList (Id,CountryISOCode,Country) values(226,'TT','TRINIDAD AND TOBAGO')
insert into tblCountryList (Id,CountryISOCode,Country) values(227,'TN','TUNISIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(228,'TR','TURKEY')
insert into tblCountryList (Id,CountryISOCode,Country) values(229,'TM','TURKMENISTAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(230,'TC','TURKS AND CAICOS ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(231,'TV','TUVALU')
insert into tblCountryList (Id,CountryISOCode,Country) values(232,'UG','UGANDA')
insert into tblCountryList (Id,CountryISOCode,Country) values(233,'UA','UKRAINE')
insert into tblCountryList (Id,CountryISOCode,Country) values(234,'AE','UNITED ARAB EMIRATES')
insert into tblCountryList (Id,CountryISOCode,Country) values(235,'GB','UNITED KINGDOM')
insert into tblCountryList (Id,CountryISOCode,Country) values(236,'US','UNITED STATES')
insert into tblCountryList (Id,CountryISOCode,Country) values(237,'UM','UNITED STATES MINOR OUTLYING ISLANDS')
insert into tblCountryList (Id,CountryISOCode,Country) values(238,'UY','URUGUAY')
insert into tblCountryList (Id,CountryISOCode,Country) values(239,'UZ','UZBEKISTAN')
insert into tblCountryList (Id,CountryISOCode,Country) values(240,'VU','VANUATU')
insert into tblCountryList (Id,CountryISOCode,Country) values(241,'VE','VENEZUELA, BOLIVARIAN REPUBLIC OF')
insert into tblCountryList (Id,CountryISOCode,Country) values(242,'VN','VIET NAM')
insert into tblCountryList (Id,CountryISOCode,Country) values(243,'VG','VIRGIN ISLANDS, BRITISH')
insert into tblCountryList (Id,CountryISOCode,Country) values(244,'VI','VIRGIN ISLANDS, U.S.')
insert into tblCountryList (Id,CountryISOCode,Country) values(245,'WF','WALLIS AND FUTUNA')
insert into tblCountryList (Id,CountryISOCode,Country) values(246,'EH','WESTERN SAHARA')
insert into tblCountryList (Id,CountryISOCode,Country) values(247,'YE','YEMEN')
insert into tblCountryList (Id,CountryISOCode,Country) values(248,'ZM','ZAMBIA')
insert into tblCountryList (Id,CountryISOCode,Country) values(249,'ZW','ZIMBABWE')
